apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cogkos.serviceAccountName" . }}
  labels:
    {{- include "cogkos.labels" . | nindent 4 }}
  {{- with .Values.mcp.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.mcp.serviceAccount.automount }}
