apiVersion: v1
kind: Namespace
metadata:
  name: cogkos
  labels:
    name: cogkos
    app.kubernetes.io/name: cogkos
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
